### ISSUE TITLE
libcudart.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by itszash** [autonomousvision/occupancy_networks#67]
couple of months ago everything was running smooth but after reinstalling linux my nvidia driver updated to driver-440 with cuda 10.2 and when i tried to run demo file i got different errors because of compatibility i manged to pass all of them but now stuck on this one and don't now how to pass this. 
This is probably because of miss-match of pytorch with cuda 10.2 can you help me figure it out how make things right here?
I can't even downgrade to driver-390 or cuda 9.0.

This is what i got

**Traceback (most recent call last):
  File "generate.py", line 10, in <module>
    from im2mesh import config
  File "/home/zash/Desktop/occupancy_networks-master/im2mesh/config.py", line 4, in <module>
    from im2mesh import onet, r2n2, psgn, pix2mesh, dmc
  File "/home/zash/Desktop/occupancy_networks-master/im2mesh/dmc/__init__.py", line 1, in <module>
    from im2mesh.dmc import (
  File "/home/zash/Desktop/occupancy_networks-master/im2mesh/dmc/config.py", line 2, in <module>
    from im2mesh.dmc import models, training, generation
  File "/home/zash/Desktop/occupancy_networks-master/im2mesh/dmc/models/__init__.py", line 2, in <module>
    from im2mesh.dmc.models import encoder, decoder
  File "/home/zash/Desktop/occupancy_networks-master/im2mesh/dmc/models/encoder.py", line 4, in <module>
    from im2mesh.dmc.ops.grid_pooling import GridPooling
  File "/home/zash/Desktop/occupancy_networks-master/im2mesh/dmc/ops/grid_pooling.py", line 6, in <module>
    from ._cuda_ext import grid_pooling_forward, grid_pooling_backward
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory**

**Comment by SMY19999** [comment]
i have a same problem
RTX 3080 CUDA11.4 pytorch 1.7.0
but it returns :
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

**Comment by XiaoyanQian** [comment]
> i have a same problem RTX 3080 CUDA11.4 pytorch 1.7.0 but it returns : ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

Hi Xiaoyang, I have the same issue. Do you solve it?

**Comment by SMY19999** [comment]
Yes, I solved it. In fact, the root of the problem is that different versions of pytorch have different requirements for CUDA. You can install pytorch according to your own graphics card and CUDA. You don't have to worry that the version of pytorch must be consistent with the source code.
For example, my name is CUDA 11.4, and I have installed pytorch1.12.0+cu113, which is no problem.

&nbsp;


筱阳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Catherine ***@***.***&gt;; 
发送时间: 2023年3月15日(星期三) 晚上7:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [autonomousvision/occupancy_networks] libcudart.so.9.0: cannot open shared object file: No such file or directory (#67)





  
i have a same problem RTX 3080 CUDA11.4 pytorch 1.7.0 but it returns : ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory
  
Hi Xiaoyang, I have the same issue. Do you solve it?

**Comment by XiaoyanQian** [comment]
> Yes, I solved it. In fact, the root of the problem is that different versions of pytorch have different requirements for CUDA. You can install pytorch according to your own graphics card and CUDA. You don't have to worry that the version of pytorch must be consistent with the source code. For example, my name is CUDA 11.4, and I have installed pytorch1.12.0+cu113, which is no problem. &nbsp; 筱阳 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Catherine ***@***.***&gt;; 发送时间: 2023年3月15日(星期三) 晚上7:30 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [autonomousvision/occupancy_networks] libcudart.so.9.0: cannot open shared object file: No such file or directory (#67) i have a same problem RTX 3080 CUDA11.4 pytorch 1.7.0 but it returns : ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory Hi Xiaoyang, I have the same issue. Do you solve it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Hi 筱阳, 谢谢你哈。我能问一下呢，你python用的是它指定的3.6.7版本吗？我想问，environment.yaml 里面的python版本是不是也可以不用一致。我之前试过所有的版本号都去掉，但是后面编译会报错的。能告诉我你安装的环境吗？

**Comment by SMY19999** [comment]
我想起来了，这个O-Net我后来就没有配置了，我去用deepsdf了；

**Comment by SMY19999** [comment]
我想起来了，这个O-Net我后来就没有配置了，我去用deepsdf了；
torch ==1.12.1
CUDA 11.4
python 3.7.13

**Comment by XiaoyanQian** [comment]
> 我想起来了，这个O-Net我后来就没有配置了，我去用deepsdf了； torch ==1.12.1 CUDA 11.4 python 3.7.13 Message ID: ***@***.***&gt;
哈哈哈能告知为什么吗？是环境比较麻烦，还是其他的原因要去用signed distance了

**Comment by XiaoyanQian** [comment]
> 我想起来了，这个O-Net我后来就没有配置了，我去用deepsdf了； torch ==1.12.1 CUDA 11.4 python 3.7.13 Message ID: ***@***.***&gt;

哈哈哈能告知为什么吗？是环境比较麻烦，还是其他的原因要去用signed distance了

**Comment by SMY19999** [comment]
对，就是环境的问题；deepsdf也只是跑通了而已，为了搞懂原理。感觉deepsdf的代码写的也比较好，网络结构很简单，不像O-Net那么多层。


筱阳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "autonomousvision/occupancy_networks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月17日(星期五) 上午8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [autonomousvision/occupancy_networks] libcudart.so.9.0: cannot open shared object file: No such file or directory (#67)





  
我想起来了，这个O-Net我后来就没有配置了，我去用deepsdf了； torch ==1.12.1 CUDA 11.4 python 3.7.13 Message ID: @.***&gt;
  
哈哈哈能告知为什么吗？是环境比较麻烦，还是其他的原因要去用signed distance了

**Comment by XiaoyanQian** [comment]
> 对，就是环境的问题；deepsdf也只是跑通了而已，为了搞懂原理。感觉deepsdf的代码写的也比较好，网络结构很简单，不像O-Net那么多层。 筱阳 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "autonomousvision/occupancy_networks" ***@***.***&gt;; 发送时间:&nbsp;2023年3月17日(星期五) 上午8:07 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [autonomousvision/occupancy_networks] libcudart.so.9.0: cannot open shared object file: No such file or directory (#67) 我想起来了，这个O-Net我后来就没有配置了，我去用deepsdf了； torch ==1.12.1 CUDA 11.4 python 3.7.13 Message ID: @.***&gt; 哈哈哈能告知为什么吗？是环境比较麻烦，还是其他的原因要去用signed distance了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

明白了，我现在的环境也还是有问题，感觉以后我们可以交流交流这方面的理解

**Comment by SMY19999** [comment]
加油吧。随便装个环境都得搞一周，最后还可能因为各种依赖、什么不匹配放弃。:）


筱阳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "autonomousvision/occupancy_networks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月17日(星期五) 中午11:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [autonomousvision/occupancy_networks] libcudart.so.9.0: cannot open shared object file: No such file or directory (#67)





  
对，就是环境的问题；deepsdf也只是跑通了而已，为了搞懂原理。感觉deepsdf的代码写的也比较好，网络结构很简单，不像O-Net那么多层。 筱阳 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "autonomousvision/occupancy_networks" @.&gt;; 发送时间:&nbsp;2023年3月17日(星期五) 上午8:07 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [autonomousvision/occupancy_networks] libcudart.so.9.0: cannot open shared object file: No such file or directory (#67) 我想起来了，这个O-Net我后来就没有配置了，我去用deepsdf了； torch ==1.12.1 CUDA 11.4 python 3.7.13 Message ID: @.&gt; 哈哈哈能告知为什么吗？是环境比较麻烦，还是其他的原因要去用signed distance了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
  
明白了，我现在的环境也还是有问题，感觉以后我们可以交流交流这方面的理解

**Comment by XiaoyanQian** [comment]
Hi 筱阳， 我能问一下呢，你读onet, 还是deepsdf, 觉得他们的G round truth label 是什么呢？

**Comment by SMY19999** [comment]
我仔细看了deepSDF，因为是虚拟数据集，空间中任何一点到surface表面的距离都可以算出，这个就是GT label。
O-Net估计也是一个道理。




筱阳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "autonomousvision/occupancy_networks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [autonomousvision/occupancy_networks] libcudart.so.9.0: cannot open shared object file: No such file or directory (#67)





 
Hi 筱阳， 我能问一下呢，你读onet, 还是deepsdf, 觉得他们的G round truth label 是什么呢？

**Comment by hahahahahahahap** [comment]
在虚拟环境当中安装一个cudatoolkit 9版本应该 可能有用
